#!/usr/bin/env php
<?php

// Error logging
ini_set("display_errors", 1);
error_reporting(E_ALL);

// Change dir
chdir(__DIR__);

// Include the autoloader
require __DIR__ . '/vendor/autoload.php';

// Init Slim
$settings = require __DIR__ . '/src/settings.php';
$app = new \Slim\App($settings);

// Set up dependencies
require __DIR__ . '/src/dependencies.php';

// Start the CLI
$cli = new \Symfony\Component\Console\Application("EVE-Auth");

// Find tasks..
$tasks = array(__DIR__ . "/tasks/*.php", __DIR__ . "/tasks/CLI/*.php");

// Load all the commands
foreach ($tasks as $task) {
    $files = glob($task);
    foreach ($files as $file) {
        require_once($file);
        $file = str_replace(__DIR__ . "/", "", $file);
        $name = str_replace(".php", "", basename($file));
        $namespace = ucfirst(str_replace("/", "\\", str_replace(".php", "", $file)));
        $import = "\\EVEAuth\\{$namespace}";

        $cli->add(new $import());
    }
}

// Run the CLI
$cli->run();

// Prompter
function prompt($prompt, $default = "")
{
    echo "$prompt [$default] ";
    $answer = trim(fgets(STDIN));
    if (strlen($answer) == 0) {
        return $default == "yes" ? true : $default;
    }
    return $answer;
}